Physician Directory/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Physician_Directory.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Physician Directory/Controllers/PhysicianController.cs
using Physician_Directory.Models;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Physician_Directory.Controllers
{
    public class PhysicianController : Controller
    {
        static Physician physician = new Physician();
        static ContactInfo cont = new ContactInfo();
        static Specialization spec = new Specialization();
        // GET: Physician

        ServiceReference1.MyServiceClient ur = new ServiceReference1.MyServiceClient();

        public ActionResult Index(string searchstring)
        {
            TempData["search"] = searchstring;
            TempData.Keep();
            
            if (searchstring != null)
            {
                List<Physician> physi = new List<Physician>();


                var searchPhysician = ur.GetPhysicianByName(searchstring);

                foreach (var item in searchPhysician)
                {
                    Physician phys = new Physician();
                    phys.Id = item.Id;
                    phys.FirstName = item.FirstName;
                    phys.MiddleName = item.MiddleName;
                    phys.LastName = item.LastName;
                    phys.BirthDate = item.BirthDate;
                    phys.Gender = item.Gender;
                    phys.Height = item.Height;
                    phys.Weight = item.Weight;
                    phys.ContactInfo = new ContactInfo
                    {
                        PhysicianId = item.Id,
                        HomeAddress = item.ContactInformation.HomeAddress,
                        HomePhone = item.ContactInformation.HomePhone,
                        OfficeAddress = item.ContactInformation.OfficeAddress,
                        OfficePhone = item.ContactInformation.OfficePhone,
                        EmailAddress = item.ContactInformation.EmailAddress,
                        CellphoneNumber = item.ContactInformation.CellphoneNumber
                    };
                    phys.Specialization = new Specialization
                    {
                        PhysicianId = item.Id,
                        Name = item.Specialization.Name,
                        Description = item.Specialization.Description
                    };

                    physi.Add(phys);
                }
                TempData["physList"] = physi;
                TempData.Keep();
                return View(physi);


            }
            else
            {
                List<Physician> physi = new List<Physician>();
               
                var physlist = ur.GetPhysician();

                foreach (var item in physlist)
                {
                    Physician phy = new Physician();
                   
                    phy.Id = item.Id;
                    phy.FirstName = item.FirstName;
                    phy.MiddleName = item.MiddleName;
                    phy.LastName = item.LastName;
                    phy.BirthDate = item.BirthDate;
                    phy.Gender = item.Gender;
                    phy.Height = item.Height;
                    phy.Weight = item.Weight;
                    phy.ContactInfo = new ContactInfo {
                        PhysicianId = item.Id,
                        HomeAddress = item.ContactInformation.HomeAddress,
                        HomePhone = item.ContactInformation.HomePhone,
                        OfficeAddress = item.ContactInformation.OfficeAddress,
                        OfficePhone = item.ContactInformation.OfficePhone,
                        EmailAddress = item.ContactInformation.EmailAddress,
                        CellphoneNumber = item.ContactInformation.CellphoneNumber,
                       
                    };
                    phy.Specialization = new Specialization
                    {
                        PhysicianId = item.Id,
                        Name = item.Specialization.Name,
                        Description = item.Specialization.Description
                    };
                    // physician.ContactInfo.HomePhone = item.ContactInformation.HomePhone;
                    //  physician.ContactInfo.OfficeAddress = item.ContactInformation.OfficeAddress;
                    // physician.ContactInfo.OfficePhone = item.ContactInformation.OfficePhone;
                    //  physician.ContactInfo.EmailAddress = item.ContactInformation.EmailAddress;
                    //   physician.ContactInfo.CellphoneNumber = item.ContactInformation.CellphoneNumber;
                    //  physician.Specialization.Name = item.Specialization.Name;
                    //  physician.Specialization.Description = item.Specialization.Description;
          
                    physi.Add(phy);


                }
                TempData["physicianList"] = physi;
                TempData.Keep();
                return View(physi);
            }
               
        
        }



        public ActionResult ViewContactInfo()

        {


            if (TempData["search"] != null)
            {
               
                //  var searchPhysician = physicians.Where(s => s.FirstName.ToLower().Contains(TempData["search"].ToString().ToLower()) || s.MiddleName.ToLower().Contains(TempData["search"].ToString().ToLower()) || s.LastName.ToLower().Contains(TempData["search"].ToString().ToLower()));
                var physList = TempData["physList"];
                TempData.Keep();
                  return View(physList);


            }
            var physicianList = TempData["physicianList"];
            TempData.Keep();
            return View(physicianList);



        }

        public ActionResult ViewSpecialization()
        {

            if (TempData["search"] != null)
            {

                //   var searchPhysician = physicians.Where(s => s.FirstName.ToLower().Contains(TempData["search"].ToString().ToLower()) || s.MiddleName.ToLower().Contains(TempData["search"].ToString().ToLower()) || s.LastName.ToLower().Contains(TempData["search"].ToString().ToLower()));

                var physList = TempData["physList"];
                TempData.Keep();
                return View(physList);
                //  return View(searchPhysician);


            }

            var physicianList = TempData["physicianList"];
            TempData.Keep();
            return View(physicianList);

        }

        // GET: Physician/Details/5
      //  public ActionResult Details(int id)
       // {
            //return View(physicians);
       // }

        // GET: Physician/Create
        public ActionResult CreatePhysician()
        {

            return View();
        }

        // POST: Physician/Create
        [HttpPost]
        //[ActionName("Create")]
        //public ActionResult formCollection(FormCollection collection, string nextBtn, string prevBtn)
        public ActionResult CreatePhysician(FormCollection collection, string nextBtn, string prevBtn)
        {
            try
            {


                var lastPhysicianId = ur.GetPhysician().Any(phys => phys.Id >= 1);

                if (nextBtn != null)
                {

                    if (ModelState.IsValid)
                    {
                        if (lastPhysicianId)
                        {
                            physician.Id = ur.GetPhysician().Max(item => item.Id) + 1;
                        }

                        else
                        {
                            physician.Id = 1;
                        }

                        physician.FirstName = collection["FirstName"];
                        physician.MiddleName = collection["MiddleName"];
                        physician.LastName = collection["LastName"];
                        DateTime jDate;
                        //bool isDateFormat = !DateTime.TryParseExact(collection["BirthDate"], "MM/dd/yyyy", null, System.Globalization.DateTimeStyles.None, out jDate);
                        //if (isDateFormat)
                        //{
                        //     ModelState.AddModelError("BirthDate", "Error Format");

                        //   return View(physician);
                        //}
                        DateTime.TryParse(collection["BirthDate"], out jDate);
                        physician.BirthDate = jDate;

                        physician.Gender = collection["Gender"];


                        double weight;
                        double.TryParse(collection["Weight"], out weight);
                        physician.Weight = weight;
                        double height;
                        double.TryParse(collection["Height"], out height);
                        physician.Height = height;



                        return View("AddContactInfo", cont);
                    }


                }


                return View();

            }
            catch
            {
                return View();
            }
        }
        // GET: Physician/Create
        public ActionResult AddContactInfo()
        {

            return View(cont);
        }


        [HttpPost]
        public ActionResult AddContactInfo(FormCollection collection, string prevBtn, string nextBtn)
        {
            try
            {


                if (prevBtn != null)
                {




                    return View("CreatePhysician", physician);

                }
                if (nextBtn != null)
                {
                    if (ModelState.IsValid)
                    {
                        cont.PhysicianId = physician.Id;
                        cont.HomeAddress = collection["HomeAddress"];
                        cont.HomePhone = (collection["HomePhone"]);
                        cont.OfficeAddress = collection["OfficeAddress"];
                        cont.OfficePhone = (collection["OfficePhone"]);
                        cont.EmailAddress = collection["EmailAddress"];

Physician Directory/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Physician Directory/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Physician Directory/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@Styles.Render("~/Content/css")
@Styles.Render("~/Content/Home.css")

<div id="menu">


    <div class="hims-menu">
        <div id="physician-directory-menu">
            <h4> Physician Directory</h4>
            <p>At HIMS, our mission is to improve the health of people through excellence in patient care and medical discovery. With more than 1300 full-time physicians, we are honored to serve you.</p>


            @Html.ActionLink(">> Physician Directory", "Index", "Physician", null, new { @id = "view-physician-directory" })

        </div>

    </div>

    <div class="hims-menu">
        <div id="physician-directory-menu">
            <h4>Appointment Request Calendar</h4>
            <p>
                To get started, simply click on <a href="www.google.com">Request an Appointment</a>.
                <br />

                Our scheduling office will contact you to schedule your appointment!
            </p>

        </div>

    </div>

    <div class="hims-menu">
        <div id="physician-directory-menu">
            <h4> Accounting and Billing</h4>
            <p>
                If you have questions about your bill, please contact our hospital business office at 540-316-2970. For questions about your bill, call Patient Accounts at 540-316-2973.
            </p>
            @Html.ActionLink(">> Accounting and Billing", "Index", "Physician", null, new { @id = "view-accounting" })
        </div>

    </div>

    <div class="hims-menu">
        <div id="physician-directory-menu">
            <h4>Pharmacy Inventory</h4>
            <p>The Helix inventory control and purchase order system is a realtime perpetual inventory system.</p>
            @Html.ActionLink(">> Pharmacy Inventory", "Index", "Physician", null, new { @id = "view-pharmacy-inventory" })
        </div>

    </div>




    <div class="hims-menu">
        <div id="physician-directory-menu">
            <h4> In-patient Monitoring</h4>
            <p>Activity monitoring has the potential to engage patients as advocates in their personalized care, as well as offer health care providers real world assessments of their patients’ daily activity patterns.</p>
            @Html.ActionLink(">> In-Patient Monitorning", "Index", "Physician", null, new { @id = "in-patient-monitoring" })
        </div>

    </div>

    <div class="hims-menu">
        <div id="physician-directory-menu">
            <h4>Room / Equipment Reservation</h4>
            <p>To request a room or equipment reservation click <a href="www.google.com">here</a>.</p>
            <br />
        </div>

    </div>

    <div class="hims-menu">
        <div id="physician-directory-menu">
            <h4>Patient Medical History</h4>
            <p>A medical record is a complete information of a patient’s key clinical data and medical history, such as vital signs, diagnoses, medications, treatment plans, allergies, radiology images, and laboratory results.</p>
            @Html.ActionLink(">> Patient Medical History", "Index", "Physician", null, new { @id = "patient-medical-history" })
        </div>

    </div>

    <div class="hims-menu">
        <div id="physician-directory-menu">
            <h4>  User Account Administration</h4>
            <p>Update account information <a href="www.google.com">here</a>.</p>

        </div>

    </div>

   


    <div>
        <img src="http://www.ramiromedical.org/images/ramiro-logo-fix.png" id="hims-icon" />
        <h4 id="hims-label">Hospital Information Management System</h4>


    </div>



</div>

<!-- <div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>
    -->